- name: vjunos ros BGP
  hosts: vjunos_ros
  gather_facts: no
  connection: local

  tasks:
    - name: Add address list
      community.routeros.api:
        hostname: "{{ ansible_host }}"
        password: "{{ ansible_password }}"
        username: "{{ ansible_user }}"
        path: "ip firewall address-list"
        add: "address={{ item.address }} list={{ item.list }}"
      loop: "{{ ros_address_list }}"
      when: ros_address_list is defined
      ignore_errors: true

    - name: ros BGP
      when: ros_bgp is defined
      block:
        - name: Add BGP template
          community.routeros.api:
            hostname: "{{ ansible_host }}"
            password: "{{ ansible_password }}"
            username: "{{ ansible_user }}"
            path: "routing bgp template"
            add: "name={{ item.name }} router-id={{ item.router_id }} as={{ item.bgp_as }} output.network={{ item.network }}"
          loop: "{{ ros_bgp.template }}"
          ignore_errors: true

        - name: Add BGP connection
          community.routeros.api:
            hostname: "{{ ansible_host }}"
            password: "{{ ansible_password }}"
            username: "{{ ansible_user }}"
            path: "routing bgp connection"
            add: "name={{ item.name }} remote.address={{ item.raddr }} remote.as={{ item.remote_as }} templates={{ item.templates }} local.role={{ item.role }}"
          loop: "{{ ros_bgp.connection }}"
          ignore_errors: true
