- name: vjunos ros ip address
  hosts: vjunos_ros
  gather_facts: no
  connection: local

  tasks:
    - name: Add ip address
      community.routeros.api:
        hostname: "{{ ansible_host }}"
        password: "{{ ansible_password }}"
        username: "{{ ansible_user }}"
        path: "ip address"
        add: "address={{ item.address }} interface={{ item.interface }}"
      loop: "{{ ros_ipaddr }}"
      when: ros_ipaddr is defined
      ignore_errors: true