- name: vjunos ros ip dhcp server
  hosts: vjunos_ros
  gather_facts: no
  connection: local

  tasks:
    - name: Add ip pool
      community.routeros.api:
        hostname: "{{ ansible_host }}"
        password: "{{ ansible_password }}"
        username: "{{ ansible_user }}"
        path: "ip pool"
        add: "name={{ item.pool.name }} ranges={{ item.pool.ranges }}"
      loop: "{{ dhcp_server }}"
      when: dhcp_server is defined
      ignore_errors: true

    - name: Add ip dhcp-server
      community.routeros.api:
        hostname: "{{ ansible_host }}"
        password: "{{ ansible_password }}"
        username: "{{ ansible_user }}"
        path: "ip dhcp-server"
        add: "name={{ item.server.name}} address-pool={{ item.server.pool }} interface={{ item.server.interface }}"
      loop: "{{ dhcp_server }}"
      when: dhcp_server is defined
      ignore_errors: true

    - name: Add ip dhcp-server network
      community.routeros.api:
        hostname: "{{ ansible_host }}"
        password: "{{ ansible_password }}"
        username: "{{ ansible_user }}"
        path: "ip dhcp-server network "
        add: "address={{ item.network.address }} dns-server={{  item.network.dns }} domain={{ item.network.domain }} gateway={{ item.network.gateway }}"
      loop: "{{ dhcp_server }}"
      when: dhcp_server is defined
      ignore_errors: true