- name: vjunos ros ip dhcp client
  hosts: vjunos_ros
  gather_facts: no
  connection: local

  tasks:
    - name: Add ip dhcp client
      community.routeros.api:
        hostname: "{{ ansible_host }}"
        password: "{{ ansible_password }}"
        username: "{{ ansible_user }}"
        path: "ip dhcp-client"
        add: "interface={{ item.interface }}"
      loop: "{{ dhcp_client }}"
      when: dhcp_client is defined