all:
  children:
    juniper:
      children:
        acx1100:

    acx1100:
      hosts:
        acx1100-mgmt.lab.dachev.lan:
          ansible_user: admin
          ansible_password: "{{ vault_junos_common_pass }}"
          ansible_host: 192.168.3.109
          ansible_connection: juniper.device.pyez

    acx1100_logical_systems:
      vars:
        ansible_host: 192.168.3.109
        ansible_user: admin
        ansible_password: "{{ vault_junos_common_pass }}"
        ansible_connection: juniper.device.pyez
        set_ls: ""
      hosts:
        acx1100_lpe01:
          logical_system: "lpe01"
        acx1100_lpe02:
          logical_system: "lpe02"
        acx1100_lp01:
          logical_system: "lp01"
        acx1100_lp02:
          logical_system: "lp02"
        acx1100_lp03:
          logical_system: "lp03"

    acx1100_ce:
      vars:
        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: community.routeros.routeros
        ansible_network_cli_ssh_type: libssh
        ansible_user: admin
        ansible_password: "{{ vault_junos_common_pass }}"
        ansible_ssh_pass: "{{ vault_junos_common_pass }}"
      hosts:
        acx-ce101.lab.dachev.lan:
        acx-ce102.lab.dachev.lan:
        acx-ce201.lab.dachev.lan:
        acx-ce202.lab.dachev.lan:
