# to delete config add: -e jcmd=delete

- name: Set set command if logical-systems
  vars:
    jcmd: "set"
  ansible.builtin.set_fact:
    set_cmd: "{{ jcmd ~ ' logical-systems ' ~ logical_system ~ ' ' if logical_system is defined and logical_system else 'set ' }}"
