# ansible-playbook playbooks/juniper/check_netconf.yml

- name: juniper netconfig check
  hosts: juniper
  gather_facts: no

  tasks:
    - name: Checking NETCONF connectivity
      wait_for: 
        host: "{{ ansible_host }}"
        port: 830 
        timeout: 5