# ansible-playbook playbooks/juniper/check_netconf.yml -e 'group=acx1100'
# ansible-playbook playbooks/juniper/check_netconf.yml -e 'group=vjr'


- name: juniper netconfig check
  hosts: "{{ group }}"
  gather_facts: no

  tasks:
    - name: Checking NETCONF connectivity
      wait_for: 
        host: "{{ ansible_host }}"
        port: 830 
        timeout: 5