# we want ot use --forks since logical systems commits make conflicts 
# set {{ group }} as extra var in order to reuse this playbook for multiple groups
# ansible-playbook playbooks/juniper/common.yml  -e 'group=juniper'
# ansible-playbook playbooks/juniper/common.yml  -e 'group=acx1100_logical_systems' --forks 1
#
# to delete config add: -e 'jcmd=delete'

- name: juniper common
  hosts: "{{ group }}"
  gather_facts: false

  tasks:
    - name: Load Set commands tasks
      import_tasks: tasks/set_command.yml

    - name: Build list of Set commands - router id
      ansible.builtin.set_fact:
        set_commands: "{{ set_commands | default([]) + [ 
          set_cmd ~ 'routing-options router-id ' ~ junos_routerid
        ] }}"

    - name: Load Set commands tasks
      import_tasks: tasks/load_set_commands.yml
