# we want ot use --forks since logical systems commits make conflicts 
# set {{ group }} as extra var in order to reuse this playbook for multiple groups
# ansible-playbook playbooks/juniper/interfaces.yml  -e 'group=juniper'
# ansible-playbook playbooks/juniper/interfaces.yml  -e 'group=acx1100_logical_systems' --forks 1
#
# to delete config add: -e 'jcmd=delete'

- name: juniper interfaces
  hosts: "{{ group }}"
  gather_facts: false

  tasks:
    - name: Load Set commands tasks
      import_tasks: tasks/set_command.yml

    - name: Build list of Set commands
      ansible.builtin.set_fact:
        set_commands: "{{ set_commands | default([]) + [ 
          set_cmd ~ 'interfaces ' ~ item.0.name ~ ' ' ~ item.1
        ] }}"
      with_subelements:
        - "{{ junos_interfaces }}"
        - config

    - name: Load Set commands tasks
      import_tasks: tasks/load_set_commands.yml

