# we want ot use --forks since logical systems commits make conflicts 
# set {{ group }} as extra var in order to reuse this playbook for multiple groups
# ansible-playbook playbooks/juniper/ldp.yml  -e 'group=acx1100'
# ansible-playbook playbooks/juniper/ldp.yml  -e 'group=acx1100_logical_systems' --forks 1
#
# to delete config add: -e 'jcmd=delete'

- name: juniper ldp
  hosts: "{{ group }}"
  gather_facts: false

  tasks:
    - name: Load Set commands tasks
      import_tasks: tasks/set_command.yml

    - name: Build list of Set commands ldp
      ansible.builtin.set_fact:
        set_commands: "{{ set_commands | default([]) + [
          set_cmd ~ 'protocols ldp interface ' ~ item.name,
        ] }}"
      loop: "{{ junos_ldp.interfaces }}"

    - name: Build list of Set commands ldp conifg
      ansible.builtin.set_fact:
        set_commands: "{{ set_commands | default([]) + [
          set_cmd ~ 'protocols ldp ' ~ item 
        ] }}"
      loop: "{{ junos_ldp.config }}"
      when: junos_ldp.config is defined

    - name: Load Set commands tasks
      import_tasks: tasks/load_set_commands.yml
