junos_interfaces:
  - name: lo0
    config:
      - unit 11 description {{ inventory_hostname }}-loopback
      - unit 11 family inet address 10.0.0.11/32
  - name: ge-0/0/5
    config:
      - unit 0 description lpe01_ge-0/0/1
      - unit 0 family inet address 10.0.15.2/30
  - name: ge-0/0/2
    config:
      - unit 0 description lp02-ge-0/0/6
      - unit 0 family inet address 10.0.26.1/30
  - name: ge-0/1/0
    config:
      - unit 0 description lp03-ge-0/1/1
      - unit 0 family inet address 10.1.10.1/30
