# https://www.juniper.net/documentation/us/en/software/junos/mpls/topics/topic-map/ldp-configuration.html#id-configuring-fec-deaggregation

junos_ldp:
  transport_address: "{{ junos_routerid }}"
  deaggregate: True
  interfaces:
    - name: ge-0/0/1.0
    - name: ge-0/0/2.0
    - name: ge-0/0/4.0
