junos_interfaces:
  - name: lo0
    config:
      - unit 2 description {{ inventory_hostname }}-loopback
      - unit 2 family inet address {{ junos_routerid }}/32
  - name: ge-0/0/7
    config:
      - unit 0 description lp02_ge-0/0/3
      - unit 0 family inet address 10.0.37.2/30
  - name: ge-0/0/4
    config:
      - unit 102 description acx-ce102.lab.dachev.lan
      - unit 102 vlan-id 102
      - unit 102 family inet address 192.168.102.2/30
      - unit 202 description acx-ce202.lab.dachev.lan
      - unit 202 vlan-id 202
      - unit 202 family inet address 192.168.202.1/30
