junos_isis:
  iso_address: "49.0001.0010.0000.0002.00"
  interfaces:
    - name: ge-0/0/5.0 point-to-point ldp-synchronization # commen ld-syn for rsvp
    - name: ge-0/0/7.0 point-to-point ldp-synchronization # commen ld-syn for rsvp
    - name: lo0.2
