junos_interfaces:
  - name: ge-0/1/0 
    config:
      - media-type copper
  - name: ge-0/1/1
    config:
      - media-type copper
  - name: ge-0/1/2
    config:
      - media-type copper
  - name: ge-0/1/3
    config:
      - media-type copper
  - name: ge-0/0/4
    config:
       - flexible-vlan-tagging

