# we want ot use --forks since logical systems commits make conflicts 
# ansible-playbook playbooks/juniper/logical_systems_mpls_ldp.yml --forks 1

- name: juniper logical system LDP
  hosts: juniper_logical_systems
  gather_facts: false
  connection: local

  tasks:
    - name: Set interfaces MPLS
      juniper.device.config:
        load: 'set'
        commit: true
        lines:
          - set interfaces {{ item }} family mpls
          - set protocols mpls interface {{ item }}
      loop: "{{ mpls.interfaces }}"
      tags:
       - impls

    - name: Set interfaces LDP
      juniper.device.config:
        load: 'set'
        commit: true
        lines:
          - set protocols ldp interface {{ item }}
      loop: "{{ ldp.interfaces }}"
      tags:
       - ildp

    - name: Configure LDP
      juniper.device.config:
        load: 'set'
        commit: true
        lines:
          - set protocols ldp longest-match
          - set protocols ldp track-igp-metric

    - name: Set interfaces isis family ldp-synchronization
      juniper.device.config:
        load: 'set'
        commit: true
        lines:
          - set protocols isis interface {{ item }} ldp-synchronization
      loop: "{{ isis.interfaces }}"
      tags:
       - isis_iso