# we want ot use --forks since logical systems commits make conflicts 
# ansible-playbook playbooks/juniper/logical_systems_routing.yml --forks 1

- name: juniper logical system routing options
  hosts: juniper_logical_systems
  gather_facts: false
  connection: local

  tasks:
    - name: Configure common policy options
      juniper.device.config:
        load: 'set'
        commit: true
        lines:
          - set policy-options policy-statement load-balancing-policy then load-balance per-flow

    - name: Configure common routing options
      juniper.device.config:
        load: 'set'
        commit: true
        lines:
          - set routing-options router-id {{ router_id }}
          - set routing-options autonomous-system {{ autonomous_system }}
          - set routing-options forwarding-table export load-balancing-policy
