# we want ot use --forks since logical systems commits make conflicts 
# ansible-playbook playbooks/juniper/logical_systems_mpls_l3vpn.yml --forks 1

- name: juniper logical system mpla l3vpn
  hosts: juniper_logical_systems
  gather_facts: false
  connection: local

  tasks:
    - name: Configure LS iBGP
      when: l3vpn is defined
      block:
        - name: Set l3vpn iBGP group
          juniper.device.config:
            load: 'set'
            commit: true
            lines:
              - set protocols bgp group {{ item.name }} type internal
              - set protocols bgp group {{ item.name }} local-address {{ item.local_address }}
              - set protocols bgp group {{ item.name }} family {{ item.family }}
              - set protocols bgp group {{ item.name }} neighbor {{ item.neighbor }}
          loop: "{{ l3vpn.ibgp.groups }}"
          tags:
           - l3vpn_ibgp

        - name: Set l3vpn routing-instances
          juniper.device.config:
            load: 'set'
            commit: true
            lines:
              - set routing-instances {{ item.name }} protocols bgp group {{ item.bgp.group }} type external
              - set routing-instances {{ item.name }} protocols bgp group {{ item.bgp.group }} peer-as {{ item.bgp.peer_as }}
              - set routing-instances {{ item.name }} protocols bgp group {{ item.bgp.group }} neighbor {{ item.bgp.neighbor }}
              - set routing-instances {{ item.name }} instance-type vrf
              - set routing-instances {{ item.name }} interface {{ item.interfaces }}
              - set routing-instances {{ item.name }} route-distinguisher {{ router_id }}:{{ item.rd_id }}
              - set routing-instances {{ item.name }} vrf-target target:{{ autonomous_system }}:{{ item.rd_id }}
          loop: "{{ l3vpn.routing_instances }}"
          tags:
           - l3vpn_ri
