- name: juniper logical system root host
  hosts: juniper_logical_systems_root
  gather_facts: false
  connection: local

  tasks:
    - name: Set tunnel-services
      juniper.device.config:
        load: 'set'
        lines:
          - set chassis fpc 0 pic 0 tunnel-services bandwidth {{ junos_tunnel_services_bandwidth }}
      tags:
        - ts

    - name: Set logical systems and users
      juniper.device.config:
        load: 'set'
        lines:
          - set logical-systems {{ item.name }}
          - set system login class {{ item.lsadmin.login_class }} logical-system {{ item.name }}
          - set system login class {{ item.lsadmin.login_class }} permissions {{ item.lsadmin.permissions }}
          - set system login user {{ item.lsadmin.user }} class {{ item.lsadmin.login_class }} authentication  encrypted-password {{ item.lsadmin.pass }}
      loop: "{{ junos_logical_system_root }}"
      tags:
        - ls

    - name: Add interfaces to logical systems
      juniper.device.config:
        load: 'set'
        lines:
          - set logical-systems {{ item.0.name }} interfaces {{ item.1 }}
      with_subelements:
       - "{{ junos_logical_system_root }}"
       - "interfaces"
      tags:
        - lsi

    - name: Add logical tunnel interfaces to logical systems
      juniper.device.config:
        load: 'set'
        lines:
          - set logical-systems {{ item.0.name }} interfaces {{ junos_tunnel_int }} unit {{ item.1.unit }} encapsulation  {{ item.1.encap }} peer-unit {{ item.1.peer }}
      with_subelements: 
       - "{{ junos_logical_system_root }}"
       - "logical_tuunels"
      tags:
        - lslt

    - name: Set l2vpn CE interface (must be done on root ls)
      juniper.device.config:
        load: 'set'
        commit: true
        lines:
          - set interfaces {{ item.ce_int }} encapsulation ethernet-ccc
          - set interfaces {{ item.ce_int }} unit {{ item.ce_int_unit }} family ccc
      loop: "{{ l2vpn_ce_int }}"
      tags:
       - l2vpn_ceint

    - name: Set chassis mode
      juniper.device.config:
        load: 'set'
        commit: true
        lines:
          - set chassis network-services enhanced-ip
      tags:
       - srgb_chassis