# we want ot use --forks since logical systems commits make conflicts 
# ansible-playbook playbooks/juniper/logical_systems_mpls_l2vpn.yml --forks 1

- name: juniper logical system mpla l2vpn
  hosts: juniper_logical_systems
  gather_facts: false
  connection: local

  tasks:
    - name: Configure LS iBGP
      when: l2vpn is defined
      block:
        - name: Set l2vpn iBGP group
          juniper.device.config:
            load: 'set'
            commit: true
            lines:
              - set protocols bgp group {{ item.name }} type internal
              - set protocols bgp group {{ item.name }} local-address {{ item.local_address }}
              - set protocols bgp group {{ item.name }} family {{ item.family }}
              - set protocols bgp group {{ item.name }} neighbor {{ item.neighbor }}
          loop: "{{ l2vpn.ibgp.groups }}"
          tags:
           - l2vpn_ibgp

        - name: Set l2vpn routing-instances
          juniper.device.config:
            load: 'set'
            commit: true
            lines:
              - set routing-instances {{ item.name }} protocols l2vpn interface {{ item.ce_int }}
              - set routing-instances {{ item.name }} protocols l2vpn site {{ item.site }} interface {{ item.ce_int }} remote-site-id {{ item.remote_site_id }}
              - set routing-instances {{ item.name }} protocols l2vpn site {{ item.site }} site-identifier {{ item.local_site_id }}
              - set routing-instances {{ item.name }} protocols l2vpn encapsulation-type ethernet
              - set routing-instances {{ item.name }} instance-type l2vpn
              - set routing-instances {{ item.name }} interface {{ item.ce_int }}
              - set routing-instances {{ item.name }} route-distinguisher {{ router_id }}:{{ item.rd_id }}
              - set routing-instances {{ item.name }} vrf-target target:{{ autonomous_system }}:{{ item.rd_id }}
          loop: "{{ l2vpn.routing_instances }}"
          tags:
           - l2vpn_ri
