junos_interfaces:
  - name: lo0
    config:
      - unit 13 description {{ inventory_hostname }}-loopback
      - unit 13 family inet address 10.0.0.13/32
  - name: ge-0/1/1
    config:
      - unit 0 description lp01-ge-0/0/1
      - unit 0 family inet address 10.1.10.2/30
  - name: ge-0/1/2
    config:
      - unit 0 description lp02-ge-0/1/3
      - unit 0 family inet address 10.1.23.2/30
