download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/juniper-device-1.0.8.tar.gz
format_version: 1.0.0
name: device
namespace: juniper
server: https://galaxy.ansible.com/api/
signatures: []
version: 1.0.8
version_url: /api/v3/plugin/ansible/content/published/collections/index/juniper/device/versions/1.0.8/
