junos_isis:
  iso:
    interface: lo0.2
    address: "49.0001.0010.0000.0002.00"
  interfaces:
    - name: "{{ junos_lt_interface }}.4"
      config:
        - point-to-point ldp-synchronization # commen ld-syn for rsvp
    - name: "{{ junos_lt_interface }}.8"
      config:
        - point-to-point ldp-synchronization # commen ld-syn for rsvp
    - name: lo0.2
